# TensorFlow Workflow

after: https://www.tensorflow.org/versions/r0.12/get_started/index.html

_Just to get a feeling for the basic code layout_ ...

In [1]:
import tensorflow as tf
import numpy as np

Create a dataset that is perfect for linear regression ;-)

In [2]:
# X has 20 rows and 2 columns
X_data = np.random.uniform(-10,10,(20,2))
X_data[:,1] = X_data[:,1] * 20 + 2
print(X_data.shape)
X_data

(20, 2)


array([[  -3.1018754 ,  -62.7304139 ],
       [  -2.12574666, -129.18560592],
       [  -7.37152683,  -75.52925676],
       [  -0.71957311,   38.75096929],
       [  -6.43972844, -174.94574881],
       [   2.88979729,  -22.39928501],
       [   4.14144182,  -33.83429152],
       [  -4.59368099,  -90.6679126 ],
       [  -8.19492806,  106.32021058],
       [  -0.38991123, -141.64182244],
       [  -2.83595347,  -42.67858726],
       [   2.39947586,  156.17894114],
       [   0.80495751,   27.27404219],
       [   9.55891775,  184.43781491],
       [   8.73485272,  136.79280099],
       [   1.68264807, -126.23694008],
       [   6.64079137,  108.79939101],
       [  -7.6601185 , -188.87438308],
       [   9.88300128,  -25.15139557],
       [  -4.67739351,   82.21387429]])

In [3]:
# Our y happens to be perfectly correlated...
y_data = 30 + 3 * X_data[:,0] - X_data[:,1]
print(y_data.shape)
y_data

(20,)


array([  83.4247877 ,  152.80836593,   83.41467627,  -10.90968862,
        185.62656349,   61.06867689,   76.25861697,  106.88686963,
       -100.90499476,  170.47208875,   64.17072684, -118.98051354,
          5.14083034, -125.76106167,  -80.58824284,  161.2848843 ,
        -58.87701689,  195.89402757,   84.80039942,  -66.24605481])

#### First, define the whole computational graph.

Declare placeholders for the data:

In [4]:
X = tf.placeholder(tf.float64, [None, 2])
y = tf.placeholder(tf.float64, [None])
X, y

(<tf.Tensor 'Placeholder:0' shape=(?, 2) dtype=float64>,
 <tf.Tensor 'Placeholder_1:0' shape=(?,) dtype=float64>)

Declare a weight vector and the bias, a scalar:

In [5]:
# the weights will be randomly initialized to small values
W = tf.Variable(tf.truncated_normal([2,1], stddev=1,dtype='float64'))
b = tf.Variable(tf.zeros([1.0], dtype='float64'))
W.get_shape(), b.get_shape()

(TensorShape([Dimension(2), Dimension(1)]), TensorShape([Dimension(1)]))

If we now tried to evaluate W, we'd get an error, as we don't have created a Session yet:

In [6]:
#W.eval()

We need to define the equation for predicting y from X:

In [7]:
# Construct a linear model
y_hat = tf.add(tf.matmul(X, W), b)
y_hat

<tf.Tensor 'Add:0' shape=(?, 1) dtype=float64>

Now, we need to define our loss function, choosing MSE.

In [8]:
loss = tf.reduce_mean(tf.square(y - tf.squeeze(y_hat)))
loss

<tf.Tensor 'Mean:0' shape=<unknown> dtype=float64>

We need to choose an optimization method and a learning rate:

In [9]:
#optimizer = tf.train.GradientDescentOptimizer(1e-5)
optimizer = tf.train.AdamOptimizer(1e-2)
train = optimizer.minimize(loss)

Lastly, before executing the computation, define a graph node to initialize the variables:

In [10]:
init = tf.initialize_all_variables()

#### Now we can run the computation:

First, create a TensorFlow Session to execute the graph:

In [11]:
sess = tf.Session()
sess.run(init)

Let's have a look at the initialized weights vector and the bias:

In [12]:
W.eval(sess)

array([[ 0.67435871],
       [-0.11817936]])

In [13]:
b.eval(sess)

array([ 0.])

Now, train the model:

In [14]:
for i in range(10000):
#for i in range(100000):
    sess.run(train, feed_dict={X:X_data, y:y_data})
    if i % 1000 == 0:
    #if i % 1000 == 0:    
        print('Step {}: W = {}, b = {}, loss = {}'.format(i,
                sess.run(W), sess.run(b), sess.run(loss, feed_dict={X:X_data, y:y_data})))


Step 0: W = [[ 0.66435871]
 [-0.12817936]], b = [ 0.01], loss = 9997.577515295707
Step 100: W = [[ 0.17554054]
 [-0.8427924 ]], b = [ 0.95403785], loss = 1237.6127295439514
Step 200: W = [[ 0.81560983]
 [-0.96758979]], b = [ 1.82987611], loss = 929.1319231098756
Step 300: W = [[ 1.51103953]
 [-0.98798137]], b = [ 2.71425816], loss = 808.4008694257975
Step 400: W = [[ 2.06895755]
 [-1.00263977]], b = [ 3.60167886], loss = 720.6076266487938
Step 500: W = [[ 2.49186286]
 [-1.01338059]], b = [ 4.48448355], loss = 654.6266303323534
Step 600: W = [[ 2.79351701]
 [-1.02073697]], b = [ 5.35938111], loss = 601.9377144824336
Step 700: W = [[ 2.99449275]
 [-1.02532323]], b = [ 6.22482503], loss = 556.9092853349332
Step 800: W = [[ 3.11837459]
 [-1.02780137]], b = [ 7.07999874], loss = 516.3285284931341
Step 900: W = [[ 3.1878236 ]
 [-1.02879725]], b = [ 7.92438187], loss = 478.61102214885057
Step 1000: W = [[ 3.22179437]
 [-1.02883216]], b = [ 8.757562], loss = 443.0735018002018
Step 1100: W = [[